name: Book

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: dart-lang/setup-dart@v1
      - name: Create local.properties
        run: make get && make book && tar -cvf book.tar /site
      - name: Upload book
        uses: actions/upload-artifact@v4
        with:
          name: Book
          path: book.tar
